version: '3.9'
# Zippy â€” developer: Matias Speratti

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: zippy
      POSTGRES_USER: zippy
      POSTGRES_PASSWORD: zippy
    ports:
      - "5432:5432"

  backend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ../services/backend:/app
    command: sh -c "npm install && npm run prisma:generate && npm run start:dev"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://zippy:zippy@postgres:5432/zippy?schema=public
    depends_on:
      - postgres
